### ISSUE TITLE
QueryProvider problem: char[1] columns being mapped to int

### ISSUE THREAD

**Issue by dheijl** [schotime/NPoco#162]
NPoco 2.7.93 

Given the following;

  - Database CharColumn datatype = char[1]
  - Poco CharColumn datatype = char

The following linq query:

    Query<T>().Where(poco => poco.CharColumn = 'X' && ...snip...) 

throws an exception when reading the char column:

``System.Data.SqlClient.SqlException : Conversion failed when converting the varchar value 'X' to data type int.
Result StackTrace:	
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
at System.Data.SqlClient.SqlDataReader.Read()
at NPoco.Database.<Query>d__7`1.MoveNext() in c:\Users\dh\Documents\Visual Studio 2013\Projects\NPoco\src\NPoco\Database.cs:regel 837
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at NPoco.Linq.QueryProvider`1.ToList() in c:\Users\dh\Documents\Visual Studio 2013\Projects\NPoco\src\NPoco\Linq\SimpleQueryProvider.cs:regel 232
at TestDb.UnitTest1.NPocoWhereTest() in c:\Users\dh\Documents\Visual Studio 2013\Projects\UpdBinDos\TestDb\UnitTest1.cs:regel 109``

Queries without the .Where() handle the mapping properly.

**Comment by schotime** [comment]
Thanks,
Can you try 2.7.96 on Nuget.
Let me know.
Adam

**Comment by dheijl** [comment]
Thanks! Will try it first thing in the morning.

Danny

**Comment by dheijl** [comment]
Fixed in 2.7.96, thanks!
