### ISSUE TITLE
Dictionary not allowing null values

### ISSUE THREAD

**Issue by makingbloke** [schotime/NPoco#225]
Consider the following code:

`var s = db.Dictionary<string, string>("select name, value from settings");`

This works correctly if the first value returned in the value column is not null. However, if the first value returned is null then the following exception is thrown. 

```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=NPoco
  StackTrace:
       at NPoco.Database.Dictionary[TKey,TValue](String sql, Object[] args) in c:\Work\Projects\NPoco\NPoco-master_dev2.0_01012015\src\NPoco\Database.cs:line 764
       at WpfTest_Console.Configuration.SQLiteSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection collection) in C:\Work\DocViewer\trunk\WIP\WpfTest\WpfTest_Console\Configuration\SQLiteSettingsProvider.cs:line 81
       at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
       at System.Configuration.SettingsBase.SetPropertyValueByName(String propertyName, Object propertyValue)
       at System.Configuration.SettingsBase.set_Item(String propertyName, Object value)
       at System.Configuration.ApplicationSettingsBase.set_Item(String propertyName, Object value)
       at WpfTest_Console.Configuration.SettingsTest.set_DateTimeTest(Nullable`1 value) in C:\Work\DocViewer\trunk\WIP\WpfTest\WpfTest_Console\Configuration\Config.cs:line 16
       at WpfTest_Console.Program.Test() in C:\Work\DocViewer\trunk\WIP\WpfTest\WpfTest_Console\Program.cs:line 40
       at WpfTest_Console.Program.Main(String[] args) in C:\Work\DocViewer\trunk\WIP\WpfTest\WpfTest_Console\Program.cs:line 164
  InnerException: 
```
Is this a fault? Looking at the source it's crashing when trying to setup converter2 on line 764 in function Dictionary when it runs value.GetType() because value is null.

Cheers

**Comment by schotime** [comment]
I have fixed this, however there is a workaround which is to ensure the first value in the result set is not null. eg if you ordered the sql by value desc then hopefully it wouldn't be null.

It has been pushed to github, but I will publish a Nuget tomorrow.

**Comment by makingbloke** [comment]
Thanks

**Comment by schotime** [comment]
Fixed in v3+
