### ISSUE TITLE
Null Exception Issues

### ISSUE THREAD

**Issue by dammysky** [schotime/NPoco#227]
I am new to Npoco and I'm trying to perform basic crud operation using Oracle Database.

Here is my connection string:
`<connectionStrings>
  <add name="oraConn" connectionString="Data Source = (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = XXXXXX)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = orcl))); User ID=XXXXXX;password=XXXXX;" providerName="System.Data.OracleClient"/>
</connectionStrings>`

I have an object like this

` [TableName("PERSON")]
    [PrimaryKey("PERSONID")]
    public class User
    {
        [Column("PERSONID")]
        public int UserID { get; set; }
        [Column("PERSON_NAME")]
        public string Username { get; set; }
    }
`
 I tried to do an insert  like this

`User u = new User()
            {
                UserID = 10,
                Username = "Adam McPherson"
            };
            using(IDatabase db = new Database("oraConn"))
            {
                var a = db.Insert(u);
                
            }
`
And I keep getting this Error:
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=NPoco
  StackTrace:
       at NPoco.DatabaseTypes.OracleDatabaseType.PreExecute(IDbCommand cmd) in d:\Adam\projects\NPoco\src\NPoco\DatabaseTypes\OracleDatabaseType.cs:line 15
       at NPoco.Database.CreateCommand(IDbConnection connection, String sql, Object[] args) in d:\Adam\projects\NPoco\src\NPoco\Database.cs:line 543
       at NPoco.Database.Insert[T](String tableName, String primaryKeyName, Boolean autoIncrement, T poco) in d:\Adam\projects\NPoco\src\NPoco\Database.cs:line 1451
       at NPoco.Database.Insert[T](String tableName, String primaryKeyName, T poco) in d:\Adam\projects\NPoco\src\NPoco\Database.cs:line 1411
       at TestingNpoco.Program.Main(String[] args) in c:\Projects\NpocoEntity\TestingNpoco\Program.cs:line 24
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

Please guide appropriately.

Thanks

**Comment by schotime** [comment]
What Oracle library are you using?

**Comment by dammysky** [comment]
I'm using Oracle.DataAccess.Client

ODAC 11.1  client on Oracle 11.1.1 database

Thanks

**Comment by schotime** [comment]
It looks like that doesn't have BindByName property on the OracleCommand object. Can you verify this by creating an OracleCommand object and seeing if there is that property "BindByName" on it?

**Comment by dammysky** [comment]
Hi Adam,

It does have the BindByName property.
Below is a sample:
           OracleConnection conn = new
OracleConnection(ConfigurationManager.ConnectionStrings["dbconn"].ConnectionString.ToString());
                OracleCommand cmd = conn.CreateCommand();
                cmd.CommandText = ("Selet sysdate from dual");
                cmd.BindByName.ToString();

Thanks.

**Comment by schotime** [comment]
Could not reproduce.

**Comment by tkc8800** [comment]
I had the same error, very frustrating.  Just in case anyone else gets this error, I fixed it by changing the providerName in the Oracle connectiong string to:

providerName="Oracle.DataAccess.Client"

Previously, I was using:

providerName="System.Data.OracleClient"
