### ISSUE TITLE
Connection must be valid and open Error with Maria DB- NPoco

### ISSUE THREAD

**Issue by Abhijth-phases** [schotime/NPoco#300]
We are using Maria DB with NPoco (version 3.1.0), for managing our database operations. But some times we are getting error saying the " Connection must be valid and open.". Below is the  stack trace :-

```

   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.CheckState()
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
  at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.<QueryImp>d__155`1.MoveNext()
    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
```

another exception happen related to this error :

```
Object reference not set to an instance of an object.
stacktrace :--    at NPoco.Database.CreateCommand(DbConnection connection, String sql, Object[] args)
   at NPoco.Database.<QueryImp>d__155`1.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
```

Please let us know your thoughts.

**Comment by schotime** [comment]
Would need to know the scenario in which you are using NPoco?

Are you using the same instance of `Database`. These should be created once per request. They are not meant to be reused (singleton).

**Comment by Abhijth-phases** [comment]
We are using NPoco in MVC web application that receive lots of concurrent web requests from different web-hooks and from users. Used FluentMapping to map model with table columns. 
For we create an instance of AppsRepository class in Controllers to do the DB operation.

```

public static class MyFactory
{
    public static DatabaseFactory DbFactory { get; set; }

    public static void Setup()
    {
        var fluentConfig = FluentMappingConfiguration.Configure(new OurMappings());
        //or individual mappings
        //var fluentConfig = FluentMappingConfiguration.Configure(new UserMapping(), ....);

        DbFactory = DatabaseFactory.Config(x =>
        {
            x.UsingDatabase(() => new Database("connString"));
            x.WithFluentConfig(fluentConfig);
            x.WithMapper(new Mapper());
        });
    }
}
```

And in our repository class we declare  'db' globally
```

public class AppsRepository
{
 IDatabase db = MyFactory.DbFactory.GetDatabase();

  public AppsSettings GetSingleApp(int appId)
        {
            AppsSettings appsSettings = new AppsSettings();
            try
            {

                appsSettings  = db.SingleOrDefault<AppsSettings>(" where app_id=@0 and deleted=0", appId);
            }
            catch (Exception ex)
            {
                LoggingManager.Log(ex);
            }
            return appsSettings ;    
    }

}

```
I got this pattern from Npoco wiki

**Comment by schotime** [comment]
What version are you running on? Have u tried the latest? 3.4.1?

**Comment by Abhijth-phases** [comment]
Thank you for replying.
We are using 3.1.0. Will try with updated version 3.4.1.

**Comment by schotime** [comment]
What is the lifetime of the `AppsRepository` object?
