### ISSUE TITLE
Error: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.

### ISSUE THREAD

**Issue by hanssens** [schotime/NPoco#425]
When deploying my webapi, as a netcoreapp2.0, to Azure I got the following error:

```
The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.
The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception.
   at System.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous)
   at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, TimeoutTimer timeout)
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, Boolean redirectedUserInstance)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   ...
```

This occurs only after a deployment, in my case to Azure, when attempting to open a SqlConnection. Locally, everything runs fine. 

Luckily, after some looking around I found [the same error on a dotnet core issue](https://github.com/dotnet/corefx/issues/18406), accompanied with the fix: **manually installing System.Data.Client** (v4.4.0) fixes the problem. 

The issue also mentions that it is not specifically related to Azure; it is a combination between SqlClient v4.3.0 or lower and netcoreapp2.0.

Therefor, it might be prudent to [update the System.Data.SqlClient to v4.4.0 in NPoco](https://github.com/schotime/NPoco/blob/master/src/NPoco/NPoco.csproj#L61) as well? This would prevent others from having this issue in the future.

**Comment by hanssens** [comment]
Awesome @schotime, thanks.

**Comment by schotime** [comment]
I'm guessing it worked with 3.9.0?

**Comment by joseclament** [comment]
I've a web job and its getting the same exception, but I am not using Microsoft.AspNetCore.All.
Using netcoreapp2.1 and runtimeIdentifiers are win10-x64;osx.10.11-x64 Any idea?

**Comment by schotime** [comment]
Add the sqlclient package?

**Comment by joseclament** [comment]
@schotime It's already been added
