### ISSUE TITLE
NPoco3  - PocoDataFactory.ForType(typeof(T)) throws exception.. An Item with the same key has already been added

### ISSUE THREAD

**Issue by billrawlinson** [schotime/NPoco#477]
I really don't understand why this does this and I really depend on being able to get the PocoData.  This worked great in v2; but something has definitely changed in v3.   I was able to work around it for getting the TableName by using TableInfoForType - but I still need the ForType method to work (or some equivalent).

Is there some other method that I can't find that will get back the PocoData for a type?

**Comment by schotime** [comment]
I would probably need more info about the exception

**Comment by billrawlinson** [comment]
Here is some sample code that causes it:

Class:  `CustomDatabase.cs`
```cs
        public string GetColumnName<TType, TProperty>(Expression<Func<TType, TProperty>> property)
        {
            // Get the property name as a string
            var expression = (MemberExpression)property.Body;
            var propertyName = expression.Member.Name;

            // Get the corresponding query column name
            var column = PocoDataFactory
                .ForType(typeof(TType)).Columns.Values
                .Where(c => c.MemberInfo.Name == propertyName)
                .SingleOrDefault();
            var columnName = column.ColumnName;

            return columnName;
        }


...
        public string GetTableName<TType, TProperty>(Expression<Func<TType, TProperty>> property)
        {
            // Get the corresponding table information
            return GetTableName(typeof(TType));
        }

        public string GetTableName(Type type)
        {
            // Get the corresponding table information
            var tableInfo = PocoDataFactory
                .ForType(type)
                .TableInfo;
            return tableInfo.TableName;
        }

```

Then calling that function from a repository class:
```cs
...
Database = new CustomDatabase(connectionString);
...

                var sql = @"
                    SELECT DISTINCT rp." + Database.GetColumnName((ReportQualifiedStudent rp) => rp.ProgramYearId) + @"
                      FROM " + Database.GetTableName(typeof(ReportQualifiedStudent)) + " rp";
```

The `PocoDataFactory.ForType(type)` fails in both instances with the error metioned.  I found a work around for the Table name `PocoDataFactory.TableInfoForType(type);`  but couldn't find a work around for getting the column names; so I've had to revert back to NPoco 2.x

**Comment by schotime** [comment]
And the stack trace of the exception?

**Comment by billrawlinson** [comment]
Stack Trace:

```
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at NPoco.PocoDataBuilder.NPoco.InitializedPocoDataBuilder.Build()
   at NPoco.FluentPocoDataFactory.ForType(Type type)
   at Aemis.Data.Databases.CustomDatabase.GetColumnName[TType,TProperty](Expression`1 property) in C:\dev\projects\AemisCloud\Aemis\Aemis.Data\Databases\CustomDatabase.cs:line 48
   at Aemis.Data.Repositories.ManyToManyLoader`4..ctor(CustomDatabase database, Expression`1 primaryIdProperty, Expression`1 primaryListProperty, Expression`1 associationPrimaryIdProperty, Expression`1 associationRelatedIdProperty, Expression`1 relatedIdProperty) in C:\dev\projects\AemisCloud\Aemis\Aemis.Data\Repositories\ManyToManyLoader.cs:line 48
   at Aemis.Data.Repositories.RegionCountyLoader..ctor(CustomDatabase database) in C:\dev\projects\AemisCloud\Aemis\Aemis.Data\Repositories\RegionCountyLoader.cs:line 11
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
```


This is the same error just happening elsewhere in my app - but calling the same method of GetColumName which calls `PocoDataFactory.ForType(type)`

If you need any other info I have made a branch for this so I can beat it up to get it into whatever condition you need it in.

**Comment by billrawlinson** [comment]
The code called to generate that stack was:

```cs
        public ManyToManyLoader(
            CustomDatabase database,
            // The property on the primary type related to the many to many table. Usually the primary key
            Expression<Func<TPrimary, int>> primaryIdProperty,
            // The property on the primary type that will store the related ids
            Expression<Func<TPrimary, List<TListType>>> primaryListProperty,
            // The property on the many to many type that references the primary type.
            Expression<Func<TManyToMany, int>> associationPrimaryIdProperty,
            // The property on the many to many type that references the related type.
            Expression<Func<TManyToMany, int>> associationRelatedIdProperty,
            // The property on the related type related to the many to many table. Usually the primary key
            Expression<Func<TRelated, int>> relatedIdProperty)
        {
...
            var associationPrimaryIdColumn = database.GetColumnName(associationPrimaryIdProperty);
....
```

**Comment by schotime** [comment]
You must have a class with duplicate property names by case on it

**Comment by billrawlinson** [comment]
how would that be possible?  
For instance the above code fails on the two following models:

```cs
using Aemis.Data.Models.Classes;
using NPoco;
using System.Collections.Generic;

namespace Aemis.Data.Models.Regions
{
    public class Region : BaseSecurableModel
    {
        public int RegionId { get; set; }

        public string Title { get; set; }
        public int SortSequence { get; set; }

        public string Url { get; set; }

        public bool IsActive { get; set; }
        public bool UsesDailyAttendance { get; set; }
        public bool UsesMonthlyAttendance { get; set; }

        public int RegionTypeId { get; set; }
        public bool SupportsEnrollmentPeriods { get; set; }
        public bool IsCorrectional { get; set; }


        [ResultColumn]
        public int? PrimaryAdminAccountId { get; set; }

		[ResultColumn]
		public List<int> CountyIds { get; set; }


        [ResultColumn]
        public List<ClassAlert> ClassAlerts { get; set; }


        [ResultColumn]
        public override string ModelTitle
        {
            get { return this.Title; }

        }
    }
}
```
and then when loading:

```cs
using NPoco;
namespace Aemis.Data.Models.RegionAdmins
{
    public class RegionAdmin : BaseSecurableModel
    {
        public int RegionAdminId { get; set; }
        public int RegionId { get; set; }
        public int AccountId { get; set; }
        public int SortSequence { get; set; }
        
        [ResultColumn]
        public override string ModelTitle
        {
            get { return ""; }

        }
    }
}

```
this is the standard pattern I've been using for my many to many relationship loading.  (A region can have many admins and the same person could admin many regions in this case).

There are no duplicate property names.  I'm not even sure how I could successfully define duplicate property names (maybe via an annotation?)

Anyway, I have just stayed on 3.9.4 because I couldn't figure out the problem and can't, currently, take the time to refactor how all of my database interactions go.  It's fine how it is I just had hoped at the time to stay at the latest version of npoco.

**Comment by billrawlinson** [comment]
Here is base security model and base model

```cs


    public abstract class BaseSecurableModel : BaseModel
    {
        [ResultColumn]
        public bool HasReport { get; set; } // can generate reports on the model
        [ResultColumn]
        public bool HasRead { get; set; } // can see the model
        [ResultColumn]
        public bool HasWrite { get; set; } // can edit an existing model
        [ResultColumn]
        public bool HasDelete { get; set; } // can delete the model
        [ResultColumn]
        public bool HasAdmin { get; set; } // can edit meta things associated with the model
    }

    public abstract class BaseModel
    {
        public BaseModel()
        {
            DateAdded = DateTime.Now;
            DateModified = DateTime.Now;
        }

        public virtual string GetSummary() 
        {
            return JsonConvert.SerializeObject(this);
        }

        public abstract string ModelTitle { get; }

        [ResultColumn]
        public string KeyCode { get; set; }

        public virtual DateTime DateAdded { get; set; }

        public virtual DateTime DateModified { get; set; }

        [ResultColumn]
        public string LogChildProperty { get; set; }

    }
```

This is about as minimum of an example as I have.  I shared this region model example because it was so basic of a model.  Basically all of my many-to-many classes are built exactly like RegionAdmins just with different names to represent the relationships.  Hopefully this is enough to illustrate the problem.  

I have a huge deadline at work that is keeping me really busy through July 16 - but after that I can try to build a very simplified example app that illustrates the issue.

**Comment by finalcut** [comment]
I'm sorry I haven't been back to build a simple example of this for you yet. I'm still planning on getting a simple example for you as soon as I can.

**Comment by schotime** [comment]
Closed as no sample received

**Comment by finalcut** [comment]
sorry - I left the job where I had that code shortly after my last comment and was never able to revisit it.
