### ISSUE TITLE
Error : Input string was not in a correct format. during Fetch<>

### ISSUE THREAD

**Issue by arunprasathv** [schotime/NPoco#502]
Getting Runtime error while executing  ==>             result.Items = Fetch<T>(sqlPage, pageArgs);

at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at PetaPoco.PocoData.<>c__DisplayClass31_0.<GetConverter>b__3(Object src) in  \PetaPoco.cs:line 6077
   at petapoco_factory_0(IDataReader )
   at PetaPoco.Database.<Query>d__49`1.MoveNext() in 
PetaPoco.cs:line 1004
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PetaPoco.Database.Fetch[T](String sql, Object[] args) in 
\Models\PetaPoco.cs:line 725
   at PetaPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, String sqlCount, Object[] countArgs, String sqlPage, Object[] pageArgs) in C:\CentralBilling\2.5.4\DataAccess\Models\PetaPoco.cs:line 805
   at PetaPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, String sql, Object[] args) in \Models\PetaPoco.cs:line 829
   at PetaPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, Sql sql) in 
\Models\PetaPoco.cs:line 847

**Comment by schotime** [comment]
I'm not sure as this is on an old version of PetaPoco of which the internals have been rewritten since then. Try NPoco then if you still get the issue report the bug.
