### ISSUE TITLE
IDictionary properties on Pocos breaks on .NET Core/Standard

### ISSUE THREAD

**Issue by CapBBeard** [schotime/NPoco#559]
Hey, I'm flying by the seat of my pants a bit here so apologies if I'm missing something obvious.

We've got some ASP.NET Core services we are migrating from Framework to Standard at the moment, and I've encountered an issue where I receive a System.InvalidProgramException ("Common Language Runtime detected an invalid program.") when I call Fetch.

After much simplifying I've found merely having an 'IDictionary' property present on a mapped POCO is enough to cause this. Simply changing it to Dictionary resolves this, however we were using IDictionary extensively in our Framework project with NPoco successfully, so I'm not quite sure what's causing this behaviour here.

Here is a stack trace:
```
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType)
   at NPoco.MemberAccessor.GetSetDelegate()
   at NPoco.MemberAccessor..ctor(Type targetType, String memberName)
   at NPoco.PocoDataBuilder.<>c.<GetMemberAccessors>b__32_0(MemberInfo memberInfo)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NPoco.PocoDataBuilder.<GetPocoMembers>d__28.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NPoco.PocoDataBuilder.<GetPocoMembers>d__28.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NPoco.PocoDataBuilder.Init()
   at NPoco.PocoDataFactory.BaseClassFalbackPocoDataBuilder(Type type)
   at NPoco.Cache`2.Get(TKey key, Func`1 factory)
   at NPoco.PocoDataFactory.ForType(Type type)
   at NPoco.Database.<Read>d__150`1.MoveNext()
   at NPoco.Database.<QueryImp>d__158`1.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at NPocoTest.Program.Main(String[] args) in D:\Code\netcoretest\NPocoTest\Program.cs:line 19
```

And minimal crashing example:
```
namespace NPocoTest
{
    class TestModel
    {
        public int Id;
        public IDictionary<int, object> Items;
    }
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new Database("DSN=test", DatabaseType.SqlServer2012, SqlClientFactory.Instance))
            {
                var obj = db.SingleOrDefault<TestModel>("SELECT * FROM table WHERE Id = @0", 123);
            }

        }
    }
}
```

Potentially of note - we're not actually populating the dictionary property with this particular database call, instead utilising it a bit later. So we're not even mapping anything to it at this point in the execution.

Again, switching to Dictionary works fine, but we do try and stick to the interfaces where possible. Possibly using the IgnoreAttribute may help too but I've not gone down this avenue, and have until this point been able to avoid decorating any of our model.

We're able to get by at this stage but figured I'd report this here. Cheers!

**Comment by schotime** [comment]
You need to create a factory to create your type.
```cs
   db.Mappers.RegisterFactory<IDictionary<int, object>>(x => new Dictionary<int, object>());
```
