### ISSUE TITLE
MySql.Data.MySqlClient.MySqlException (0x80004005): There is already an open DataReader associated with this Connection which must be closed first

### ISSUE THREAD

**Issue by naughtyGitCat** [schotime/NPoco#574]
DBFactory module
```c#
using NPoco;
using System.Data.Common;
using DBAInternalAPI.Models;
using Microsoft.Extensions.Logging;

namespace DBAInternalAPI.Services
{
    public interface IDBFactory
    {
        IDatabase GetConnection();
    }
    public class DBFactory : IDBFactory
    {
        private readonly string _connectionString;
        private  DbConnection _conn;
        private readonly ILogger _p;
        public DBFactory(IMySQLDatabaseSettings setting, ILogger<DBFactory> logger)
        {
            _p = logger;
            _connectionString = setting.ConnectionString;
        }
        public IDatabase GetConnection()
        {
 
            _conn = new MySql.Data.MySqlClient.MySqlConnection(_connectionString);
            _conn.Open();
            return new Database(_conn);

        }
    }
}

```
 controller init func
```c#
        public XXXController(ILogger<DDBController> logger, IDBFactory dbFactory)
        {
            _p = logger;
            _db = dbFactory.GetConnection();
        }
```
GET 
```
        [HttpGet("version/stat")]
        public ActionResult<StandardResponse<InstanceVersionCount>> GetVersionStat()
        {
            var sql = @"****************";
            _p.LogDebug($"Query database by {sql}");
            var data = _db.Fetch<InstanceVersionCount>(sql);
            return Json(new { statusCode = 200, data });
        }
```
When many of this type ActionResult called sametime,it crash with
```
2019-12-03 10:46:24.368 +08:00 [INF] =>[Microsoft.AspNetCore.Routing.EndpointMiddleware]=> Executed endpoint 'DBAInternalAPI.Area.MySQL.Controllers.MySQLController.GetVersionStat (DBAInternalAPI)'
2019-12-03 10:46:24.369 +08:00 [ERR] =>[Microsoft.AspNetCore.Server.Kestrel]=> Connection id "0HLRN5RMTIDGS", Request id "0HLRN5RMTIDGS:00000001": An unhandled exception was thrown by the application.
MySql.Data.MySqlClient.MySqlException (0x80004005): There is already an open DataReader associated with this Connection which must be closed first.
   at MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DBAInternalAPI.Area.MySQL.Controllers.MySQLController.GetVersionStat() in /Users/psyduck/Projects/SAL/DBAInternalAPI/Areas/MySQL/Controllers/MySQLController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by naughtyGitCat** [comment]
After add this to controller
```c#
        protected override void Dispose(bool disposing)
        {
            _p.LogDebug($"Time to Dispose {this.GetType()}");
            _db.Connection.CloseAsync();
            _db.Dispose();
        }
```

the error change to 
```
2019-12-05 21:10:06.399 +08:00 [DBG] =>[DBAInternalAPI.Areas.MySQL.Controllers.MongoDBController]=> Time to Dispose DBAInternalAPI.Areas.MySQL.Controllers.MongoDBController
2019-12-05 21:10:06.399 +08:00 [INF] =>[Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker]=> Executed action DBAInternalAPI.Areas.MySQL.Controllers.MongoDBController.GetVersionStat (DBAInternalAPI) in 3.576ms
2019-12-05 21:10:06.400 +08:00 [INF] =>[Microsoft.AspNetCore.Routing.EndpointMiddleware]=> Executed endpoint 'DBAInternalAPI.Areas.MySQL.Controllers.MongoDBController.GetVersionStat (DBAInternalAPI)'
2019-12-05 21:10:06.400 +08:00 [ERR] =>[Microsoft.AspNetCore.Server.Kestrel]=> Connection id "0HLRPFH8P51NL", Request id "0HLRPFH8P51NL:00000001": An unhandled exception was thrown by the application.
System.Exception: You must explicitly open the connection before executing anything when passing in a DbConnection to Database
   at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal)
   at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NPoco.Database.Fetch[T](Sql sql)
   at NPoco.Database.Fetch[T](String sql, Object[] args)
   at DBAInternalAPI.Areas.MySQL.Controllers.MongoDBController.GetVersionStat() in /Users/psyduck/Projects/SAL/DBAInternalAPI/Areas/MongoDB/Controllers/MongoDBController.cs:line 47
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2019-12-05 21:10:06.402 +08:00 [INF] =>[Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker]=> Executed action DBAInternalAPI.Area.MySQL.Controllers.MySQLController.GetVersionStat (DBAInternalAPI) in 6.313400000000001ms
2019-12-05 21:10:06.402 +08:00 [INF] =>[Microsoft.AspNetCore.Routing.EndpointMiddleware]=> Executed endpoint 'DBAInternalAPI.Area.MySQL.Controllers.MySQLController.GetVersionStat (DBAInternalAPI)'
2019-12-05 21:10:06.403 +08:00 [ERR] =>[Microsoft.AspNetCore.Server.Kestrel]=> Connection id "0HLRPFH8P51NK", Request id "0HLRPFH8P51NK:00000001": An unhandled exception was thrown by the application.
MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered during command execution.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Invalid attempt to call NextResult when the reader is closed.
   at MySql.Data.MySqlClient.MySqlDataReader.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.Driver.LoadServerProperties(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at DBAInternalAPI.Services.DBFactory.GetConnection() in /Users/psyduck/Projects/SAL/DBAInternalAPI/Services/DBFactory.cs:line 28
   at DBAInternalAPI.Area.MySQL.Controllers.MySQLController..ctor(IDBFactory dbFactory, ILogger`1 logger, IDiagnosticContext diagnosticContext) in /Users/psyduck/Projects/SAL/DBAInternalAPI/Areas/MySQL/Controllers/MySQLController.cs:line 33
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2019-12-05 21:10:06.404 +08:00 [INF] =>[Microsoft.AspNetCore.Hosting.Diagnostics]=> Request finished in 21.8317ms 500
```

**Comment by naughtyGitCat** [comment]
@schotime

**Comment by naughtyGitCat** [comment]
```c#
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<MySQLDatabaseSettings>(Configuration.GetSection(nameof(MySQLDatabaseSettings)));
            services.AddControllers()
                .AddNewtonsoftJson(options => options.UseCamelCasing(true));
            services.AddSwaggerDocument();
          

            services.AddSingleton<IMySQLDatabaseSettings>(sp =>
            sp.GetRequiredService<IOptions<MySQLDatabaseSettings>>().Value);
            services.AddSingleton<IDBFactory,DBFactory>();

```

**Comment by naughtyGitCat** [comment]
```c#
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<MySQLDatabaseSettings>(Configuration.GetSection(nameof(MySQLDatabaseSettings)));
            services.AddControllers()
                .AddNewtonsoftJson(options => options.UseCamelCasing(true));
            services.AddSwaggerDocument();
          

            services.AddSingleton<IMySQLDatabaseSettings>(sp =>
            sp.GetRequiredService<IOptions<MySQLDatabaseSettings>>().Value);
            services.AddSingleton<IDBFactory,DBFactory>();

```

**Comment by naughtyGitCat** [comment]
change `services.AddSingleton<IDBFactory,DBFactory>();` => `services.AddScoped<IDBFactory,DBFactory>();` take effects;
but does this mean every controller will hold a connection?

**Comment by schotime** [comment]
Firstly, Database is supposed to be scoped. Its not safe across threads.
Secondly, you can allow multiple open data readers through connection string options if thats what you need also.
