### ISSUE TITLE
Can't use raw sql to insert email info to table

### ISSUE THREAD

**Issue by naughtyGitCat** [schotime/NPoco#585]
```
2020-03-27 21:35:49.190 +08:00 [WRN] =>[DBAResourceTagAPI.Controllers.HostTagController]=> NewHostTag failed, System.ArgumentException: Parameter '@corp' specified but none of the passed arguments have a property with this name (in '
                            INSERT INTO
                                xxx.xyyy
                            SET
                                host_ip='zzzz',
                                tag_name='malfunction',
                                tag_type='cccccc',
                                tag_kanji='1111111',
                                create_by='x@iiii.com',
                                update_by='x@iiii.com'
                            ON DUPLICATE KEY UPDATE
                                update_by='x@iiii''
                            ')
   at NPoco.ParameterHelper.ProcessParam(String& sql, String rawParam, Object[] args_src, List`1 args_dest, Boolean reuseParameters)
   at NPoco.ParameterHelper.<>c__DisplayClass1_0.<ProcessParams>b__0(Match m)
   at System.Text.RegularExpressions.Regex.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at NPoco.ParameterHelper.ProcessParams(String sql, Object[] args_src, List`1 args_dest, Boolean reuseParameters)
   at NPoco.Sql.Build(StringBuilder sb, List`1 args, Sql lhs)
   at NPoco.Sql.Build()
   at NPoco.Sql.get_SQL()
   at NPoco.Database.Execute(Sql Sql)
   at NPoco.Database.Execute(String sql, Object[] args)
   at DBAResourceTagAPI.Services.HostTagService.AddHostTag(String hostIP, String TagName, String requestUser)
   at DBAResourceTagAPI.Controllers.HostTagController.NewHostTag(String hostIP, String tagName)
```

**Comment by naughtyGitCat** [comment]
```c#
        public void AddHostTag(string hostIP, string TagName, string requestUser)
        {
            var t = this.FetchTagBaseInfo(TagName);
            if (t.ID>0)
            {
                using var trx = this.database.GetTransaction();
                var sql = @$"
                            INSERT INTO
                                hal_tag.tag_host
                            SET
                                host_ip='{hostIP}',
                                tag_name='{t.TagName}',
                                tag_type='{t.TagType}',
                                tag_kanji='{t.TagKanji}',
                                create_by='{requestUser}',
                                update_by='{requestUser}'
                            ON DUPLICATE KEY UPDATE
                                update_by='{requestUser}'
                            ";
                this.logger.LogDebug($"Now execute: {sql}");
                this.database.Execute(sql);
                if (t.TagInheritable == 1)
                {
                    var instanceSQL = @$"
                                         INSERT INTO
                                            hal_tag.tag_instance
                                         (instance_ip, instance_port, instance_type,
                                          tag_name, tag_type, tag_kanji,
                                          create_by, update_by)
                                         SELECT
                                           host_ip,process_port,process_name,
                                           '{t.TagName}', '{t.TagType}', '{t.TagKanji}',
                                            '{requestUser}', '{requestUser}'
                                         FROM undo_meta.host_process_port
                                         ON DUPLICATE KEY UPDATE
                                            tag_name='{t.TagName}',
                                            tag_type='{t.TagType}',
                                            tag_kanji='{t.TagKanji}',
                                            update_by='{requestUser}',
                                            update_time=NOW()
                                        ";
                    this.logger.LogDebug($"Now execute: {instanceSQL}");
                    this.database.Execute(instanceSQL);
                }
                trx.Complete();
            }
            else
            {
                throw new GenericException($"Specified tag: {TagName} does not exists");
            } 
        }
```

**Comment by naughtyGitCat** [comment]
incompatibility with c# @ or $ gramma sign? @schotime

**Comment by naughtyGitCat** [comment]
Is there any way to execute sql string with '@' in it ?

**Comment by schotime** [comment]
Double @.

So @@

**Comment by naughtyGitCat** [comment]
thanks,it works,

**Comment by naughtyGitCat** [comment]
but use `select * from tableX where email = '{email}'` failed, 

so i change to `select * from tableX where email = '{email.Replace("@","@@")}'`

and the real query sql is `select * from tableX where email = 'xxx@@yyy.com'`

**Comment by naughtyGitCat** [comment]
```
2021-11-29 11:04:16.935 +08:00 [WRN] =>[DBATicketAPI.Controllers.ResourceTicketController]=> System.ArgumentException: Parameter '@corp' specified but none of the passed arguments have a property with this name (in 'SELECT * FROM audit.ResourceTicket WHERE ApplyBy ='DBA@corp.netease.com'')
   at NPoco.ParameterHelper.ProcessParam(String& sql, String rawParam, Object[] args_src, List`1 args_dest, Boolean reuseParameters)
   at NPoco.ParameterHelper.<>c__DisplayClass1_0.<ProcessParams>b__0(Match m)
   at System.Text.RegularExpressions.Regex.<>c.<Replace>b__84_0(ValueTuple`5& state, Match match)
   at System.Text.RegularExpressions.RegexRunner.Scan[TState](Regex regex, String text, Int32 textstart, TState& state, MatchCallback`1 callback, Boolean reuseMatchObject, TimeSpan timeout)
   at System.Text.RegularExpressions.Regex.Run[TState](String input, Int32 startat, TState& state, MatchCallback`1 callback, Boolean reuseMatchObject)
   at System.Text.RegularExpressions.Regex.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at NPoco.ParameterHelper.ProcessParams(String sql, Object[] args_src, List`1 args_dest, Boolean reuseParameters)
   at NPoco.Sql.Build(StringBuilder sb, List`1 args, Sql lhs)
   at NPoco.Sql.Build()
   at NPoco.Database.QueryAsync[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()
   at NPoco.Database.QueryAsync[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at DBATicketAPI.Services.ResourceTicketService.GetResourceTicketsAsync(String applyBy)
   at DBATicketAPI.Controllers.ResourceTicketController.GetAsync(String applyBy)
2021-11-29 11:04:16.942 +08:00 [INF] =>[Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor]=> Executing ObjectResult, writing value of type 'DBAInternalCommon.Models.Common.StandardResponse`1[[System.Collections.Generic.IEnumerable`1[[DBATicketAPI.Models.ResourceTicketDO, DBATicketAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
```

**Comment by naughtyGitCat** [comment]
my mistake
