### ISSUE TITLE
NPoco LINQ query style does not support `.FirstOrDefault()`

### ISSUE THREAD

**Issue by naughtyGitCat** [schotime/NPoco#587]
```c#
        private string FetchVariableValue(string ip, int port, string variableName)
        {
            return this.database.Query<MySQLMetaVariableModel>()
                                .Where(x => x.InstanceIP == ip && x.InstancePort == port && x.VariableName == variableName)
                                .OrderByDescending(x => x.ID)
                                .Limit(1).ToString();
                                // .SingleOrDefault().ToString();
                                //.VariableValue;
        }
```
do not exception

```c#
        private string FetchVariableValue(string ip, int port, string variableName)
        {
            return this.database.Query<MySQLMetaVariableModel>()
                                .Where(x => x.InstanceIP == ip && x.InstancePort == port && x.VariableName == variableName)
                                .OrderByDescending(x => x.ID)
                                .Limit(1)
                                .SingleOrDefault().ToString();
        }
```
or
```c#
        private string FetchVariableValue(string ip, int port, string variableName)
        {
            return this.database.Query<MySQLMetaVariableModel>()
                                .Where(x => x.InstanceIP == ip && x.InstancePort == port && x.VariableName == variableName)
                                .OrderByDescending(x => x.ID)
                                .Limit(1)
                                .SingleOrDefault()
                                .VariableValue;
        }
```
raise exception l like below.

```c#
2020-04-28 15:37:17.098 +08:00 [ERR] =>[DBAInternalAPI.Area.MySQL.Controllers.MySQLController]=> In DBAInternalAPI.Area.MySQL.Controllers.MySQLController, GetMySQLReplicationParameters failed, System.NullReferenceException: Object reference not set to an instance of an object.
   at DBAInternalAPI.Areas.MySQL.Services.MySQLMetaCustomDemandService.FetchVariableValue(String ip, Int32 port, String variableName) in /Users/psyduck/Projects/SAL/DBAInternalAPI/Areas/MySQL/Services/MySQLMetaCustomDemandService.cs:line 69
   at DBAInternalAPI.Areas.MySQL.Services.MySQLMetaCustomDemandService.FetchReplicationParameters(String ip, Int32 port) in /Users/psyduck/Projects/SAL/DBAInternalAPI/Areas/MySQL/Services/MySQLMetaCustomDemandService.cs:line 58
   at DBAInternalAPI.Area.MySQL.Controllers.MySQLController.GetMySQLReplicationParameters(String instanceIP, Int32 instancePort) in /Users/psyduck/Projects/SAL/DBAInternalAPI/Areas/MySQL/Controllers/MySQLController.cs:line 194
```

**Comment by schotime** [comment]
FirstOrDefault is definitely supported.

**Comment by bryanboettcher** [comment]
@naughtyGitCat this is a bug in your code. The exception is a null reference.  Do not call methods (like .ToString()) on FirstOrDefault() or SingleOrDefault() without checking for "null" first.  Alternatively, if "null" is incorrect, then don't use the OrDefault versions.
