### ISSUE TITLE
Object must implement IConvertible.

### ISSUE THREAD

**Issue by SteveAndrews** [schotime/NPoco#590]
I'm getting the subject error when trying to retrieve a record from the database.

Repository:
```
public void RemoveItem(int value1, int value2)
{
    //// ERROR ON THIS LINE
    var result = this.Database.SingleOrDefault<MyTable>("WHERE Value1 = @0 AND Value2 = @1", value1, value2);

    if (result != null)
    {
        this.Database.Delete(result.Id);
    }
}
```

Poco Model:
```
[TableName("MyTable")]
[PrimaryKey("Id", AutoIncrement = false)]
public class MyTable
{
    public MyTable()
    {
        this.Id = Guid.NewGuid().ToString();
        this.CreatedDateUtc = DateTime.UtcNow;
    }

    [Column("Id")]
    public string Id { get; set; }

    [ComputedColumn] // (getutcdate())
    public DateTime CreatedDateUtc { get; set; }

    //// ISSUE WITH NULLABLE DATETIME?
    [Column("LastUpdatedDateUtc")]
    public DateTime? LastUpdatedDateUtc { get; set; }

    [Column("Value1")]
    public int Value1 { get; set; }

    [Column("Value2")]
    public int Value2 { get; set; }
}
```

Create script for table in SQL:
```
CREATE TABLE [dbo].[MyTable](
	[Id] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[Value1] [int] NOT NULL,
	[Value2] [int] NOT NULL,
	[CreatedDateUtc]  AS (getutcdate()),
	[LastUpdatedDateUtc] [datetime] NULL,
 CONSTRAINT [PK_MyTable] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MyTable] ADD  CONSTRAINT [DF_MyTable_Id]  DEFAULT (newid()) FOR [Id]
GO
```

I've tried a lot of different permutations. I can't seem to figure out what the issue is, and the error message doesn't say which 'object'. I also checked the wiki and didn't see anything related. I seem to be doing everything correctly, but what am I doing wrong?

**Comment by schotime** [comment]
Have you got the actual exception there? Everything looks ok at a first glance.

**Comment by SteveAndrews** [comment]
Yeah, that's the only exception: "Object must implement IConvertible."

Stack Trace:
```
at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
at NPoco.RowMappers.PropertyMapper.MapValue(GroupResult`1 posName, Object[] values, Func`2 converter, Object instance, PocoColumn pocoColumn, Object defaultValue)
at NPoco.RowMappers.PropertyMapper.<>c__DisplayClass8_2.<BuildMapPlans>b__3(DbDataReader reader, Object[] values, Object instance)
at NPoco.RowMappers.PropertyMapper.<>c__DisplayClass7_0.<BuildMapPlan>b__1(DbDataReader reader, Object[] values, Object instance)
at NPoco.RowMappers.PropertyMapper.Map(DbDataReader dataReader, RowMapperContext context)
at NPoco.MappingFactory.Map(DbDataReader dataReader, Object instance)
at NPoco.Database.<Read>d__156`1.MoveNext()
at NPoco.Database.<QueryImp>d__164`1.MoveNext()
at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
at MyProject.Infrastructure.Data.Repositories.MyRepository.RemoveItem(Int32 value1, Int32 value2)
```

**Comment by SteveAndrews** [comment]
Looks like there's an error trying to covert a GUID to a string on line 60 of MappingHelper.cs.

I changed the ID property on my model from string to guid and now everything is working.

Can I add some content to the Wiki about PK GUID columns?
- Property type should be System.Guid
-- ```public Guid Id { get; set; }```
- AutoIncrement should be set to true
-- ```[PrimaryKey("Id", AutoIncrement = true)]```
- You don't need to initialize the property
-- ```//// Not necessary - this.Id = Guid.NewGuid();```

**Comment by SteveAndrews** [comment]
Added. https://github.com/schotime/NPoco/wiki/Using-Guid-Column-as-Primary-Key

**Comment by schotime** [comment]
thanks
