### ISSUE TITLE
[SerializedColumn] attribute: throws exception if JSON contains double quotes

### ISSUE THREAD

**Issue by shervinw** [schotime/NPoco#593]
Could not find token at index 190

   at NPoco.fastJSON.JsonParser.NextTokenCore()
   at NPoco.fastJSON.JsonParser.ParseObject()
   at NPoco.fastJSON.JsonParser.ParseValue(Boolean val)
   at NPoco.fastJSON.JsonParser.ParseArray()
   at NPoco.fastJSON.JsonParser.ParseValue(Boolean val)
   at NPoco.fastJSON.deserializer.ToObject(String json, Type type)
   at NPoco.FastJsonColumnSerializer.Deserialize(String value, Type targetType)
   at NPoco.MappingHelper.<>c__DisplayClass2_0.<GetConverter>b__2(Object src)
   at NPoco.RowMappers.PropertyMapper.MapValue(GroupResult`1 posName, Object[] values, Func`2 converter, Object instance, PocoColumn pocoColumn, Object defaultValue)
   at NPoco.RowMappers.PropertyMapper.<>c__DisplayClass8_2.<BuildMapPlans>b__3(DbDataReader reader, Object[] values, Object instance)
   at NPoco.RowMappers.PropertyMapper.<>c__DisplayClass8_1.<BuildMapPlans>b__2(DbDataReader reader, Object[] values, Object instance)
   at NPoco.RowMappers.PropertyMapper.<>c__DisplayClass7_0.<BuildMapPlan>b__1(DbDataReader reader, Object[] values, Object instance)
   at NPoco.RowMappers.PropertyMapper.Map(DbDataReader dataReader, RowMapperContext context)
   at NPoco.MappingFactory.Map(DbDataReader dataReader, Object instance)
   at NPoco.Database.<Read>d__161`1.MoveNext()
   at NPoco.Database.<QueryImp>d__169`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NPoco.Linq.QueryProvider`1.ToList()
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__3(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

**Comment by schotime** [comment]
The JSON is probably invalid is my guess.

**Comment by shervinw** [comment]
doh sorry!
