### ISSUE TITLE
NullReferenceException on multiple calls to same Async Db method 

### ISSUE THREAD

**Issue by jennablackwell** [schotime/NPoco#698]
I understand that NPoco autocloses it's db connection unless specifying a shared connection.
However, I noticed in several of my projects if a call to the database happens too fast consecutively (such as doing an insert into a Log table), a "NullReferenceException" is thrown because it's saying the connection is null.  I've tried manually adding checks to make sure the connection is explicitly set and that doesn't seem to help either.  I've tried initializing a new NPoco instance to use for the db call, but that doesn't seem to help either.  Not sure there is something else going on deeper in the library code.

Db call example - this throws the exception:
 await Db.InsertAsync<MyType>(myObject);
*Note: When hovering over the "Db" object in debug, it is not null and no "myObject" is not null either.  It will work the first time executing this code but subsequent executions if too fast will throw the exception.

Exception example:
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=NPoco
  StackTrace:
   at NPoco.Database.CloseSharedConnection()
   at NPoco.Database.<InsertAsyncImp>d__3`1.MoveNext()
 

Usually I get a NullReferenceException but I've also gotten other errors such as "Connection already closed" etc.

**Comment by schotime** [comment]
The only way CloseSharedConnection() null references is if you are using the same IDatabase instance across multiple threads.

**Comment by jennablackwell** [comment]
> The only way CloseSharedConnection() null references is if you are using the same IDatabase instance across multiple threads.

Hmm.. I did try also doing something like this for my queries, but it seemed to still throw the same errors... i'll try it out once more tho.

using (IDatabase db = new Database("connStringName")) 
{
    List<User> users = db.Fetch<User>("select userId, email from users");
}
